server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: luck-eureka